# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0012_auto_20170418_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
