# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0016_auto_20170418_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBlur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UploadOriginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='original')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImageModel',
        ),
    ]
