# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0017_auto_20170419_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadblur',
            name='image',
            field=models.ImageField(default=0, upload_to='blur'),
            preserve_default=False,
        ),
    ]
